"""rename address

Revision ID: 294fb2b389de
Revises: eb605fd58366
Create Date: 2025-11-07 05:50:32.815161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294fb2b389de'
down_revision = 'eb605fd58366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
